[package]
name = "bpx"
version = "3.2.0"
authors = ["Yuri Edward <yuri6037@outlook.com>"]
edition = "2021"
description = "BPX official rust implementation"
license = "BSD-3-Clause"
repository = "https://gitlab.com/bp3d/bpx/bpx-rs"
readme = "./README.MD"
keywords = ["BPX", "encoder", "decoder"]
categories = ["encoding", "rendering::data-formats", "parser-implementations"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tempfile = "3.0.7"
byteorder = "1"
lzma-sys = "0.1.17"
num_cpus = "1.13.0"
libz-sys = "1.1.3"

[features]
debug-log = []
package = []
shader = []
