name: Release

on:
  push:
    branches:
      - master

jobs:
  Publish:
    uses: BPXFormat/workflows/.github/workflows/Publish.yml@main
    secrets:
      RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
